/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as YearRouteImport } from './app/$year'
import { Route as IndexRouteImport } from './app/index'
import { Route as YearStandingsRouteRouteImport } from './app/$year/standings/route'
import { Route as YearMapRouteRouteImport } from './app/$year/map/route'
import { Route as YearEventRouteRouteImport } from './app/$year/$event/route'
import { Route as YearStandingsIndexRouteImport } from './app/$year/standings/index'
import { Route as YearMapIndexRouteImport } from './app/$year/map/index'
import { Route as YearEventIndexRouteImport } from './app/$year/$event/index'
import { Route as YearEventSessionRouteRouteImport } from './app/$year/$event/$session/route'
import { Route as YearEventSessionIndexRouteImport } from './app/$year/$event/$session/index'

const YearRoute = YearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const YearStandingsRouteRoute = YearStandingsRouteRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => YearRoute,
} as any)
const YearMapRouteRoute = YearMapRouteRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => YearRoute,
} as any)
const YearEventRouteRoute = YearEventRouteRouteImport.update({
  id: '/$event',
  path: '/$event',
  getParentRoute: () => YearRoute,
} as any)
const YearStandingsIndexRoute = YearStandingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YearStandingsRouteRoute,
} as any)
const YearMapIndexRoute = YearMapIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YearMapRouteRoute,
} as any)
const YearEventIndexRoute = YearEventIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YearEventRouteRoute,
} as any)
const YearEventSessionRouteRoute = YearEventSessionRouteRouteImport.update({
  id: '/$session',
  path: '/$session',
  getParentRoute: () => YearEventRouteRoute,
} as any)
const YearEventSessionIndexRoute = YearEventSessionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => YearEventSessionRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$year': typeof YearRouteWithChildren
  '/$year/$event': typeof YearEventRouteRouteWithChildren
  '/$year/map': typeof YearMapRouteRouteWithChildren
  '/$year/standings': typeof YearStandingsRouteRouteWithChildren
  '/$year/$event/$session': typeof YearEventSessionRouteRouteWithChildren
  '/$year/$event/': typeof YearEventIndexRoute
  '/$year/map/': typeof YearMapIndexRoute
  '/$year/standings/': typeof YearStandingsIndexRoute
  '/$year/$event/$session/': typeof YearEventSessionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$year': typeof YearRouteWithChildren
  '/$year/$event': typeof YearEventIndexRoute
  '/$year/map': typeof YearMapIndexRoute
  '/$year/standings': typeof YearStandingsIndexRoute
  '/$year/$event/$session': typeof YearEventSessionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$year': typeof YearRouteWithChildren
  '/$year/$event': typeof YearEventRouteRouteWithChildren
  '/$year/map': typeof YearMapRouteRouteWithChildren
  '/$year/standings': typeof YearStandingsRouteRouteWithChildren
  '/$year/$event/$session': typeof YearEventSessionRouteRouteWithChildren
  '/$year/$event/': typeof YearEventIndexRoute
  '/$year/map/': typeof YearMapIndexRoute
  '/$year/standings/': typeof YearStandingsIndexRoute
  '/$year/$event/$session/': typeof YearEventSessionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$year'
    | '/$year/$event'
    | '/$year/map'
    | '/$year/standings'
    | '/$year/$event/$session'
    | '/$year/$event/'
    | '/$year/map/'
    | '/$year/standings/'
    | '/$year/$event/$session/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$year'
    | '/$year/$event'
    | '/$year/map'
    | '/$year/standings'
    | '/$year/$event/$session'
  id:
    | '__root__'
    | '/'
    | '/$year'
    | '/$year/$event'
    | '/$year/map'
    | '/$year/standings'
    | '/$year/$event/$session'
    | '/$year/$event/'
    | '/$year/map/'
    | '/$year/standings/'
    | '/$year/$event/$session/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YearRoute: typeof YearRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$year': {
      id: '/$year'
      path: '/$year'
      fullPath: '/$year'
      preLoaderRoute: typeof YearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$year/standings': {
      id: '/$year/standings'
      path: '/standings'
      fullPath: '/$year/standings'
      preLoaderRoute: typeof YearStandingsRouteRouteImport
      parentRoute: typeof YearRoute
    }
    '/$year/map': {
      id: '/$year/map'
      path: '/map'
      fullPath: '/$year/map'
      preLoaderRoute: typeof YearMapRouteRouteImport
      parentRoute: typeof YearRoute
    }
    '/$year/$event': {
      id: '/$year/$event'
      path: '/$event'
      fullPath: '/$year/$event'
      preLoaderRoute: typeof YearEventRouteRouteImport
      parentRoute: typeof YearRoute
    }
    '/$year/standings/': {
      id: '/$year/standings/'
      path: '/'
      fullPath: '/$year/standings/'
      preLoaderRoute: typeof YearStandingsIndexRouteImport
      parentRoute: typeof YearStandingsRouteRoute
    }
    '/$year/map/': {
      id: '/$year/map/'
      path: '/'
      fullPath: '/$year/map/'
      preLoaderRoute: typeof YearMapIndexRouteImport
      parentRoute: typeof YearMapRouteRoute
    }
    '/$year/$event/': {
      id: '/$year/$event/'
      path: '/'
      fullPath: '/$year/$event/'
      preLoaderRoute: typeof YearEventIndexRouteImport
      parentRoute: typeof YearEventRouteRoute
    }
    '/$year/$event/$session': {
      id: '/$year/$event/$session'
      path: '/$session'
      fullPath: '/$year/$event/$session'
      preLoaderRoute: typeof YearEventSessionRouteRouteImport
      parentRoute: typeof YearEventRouteRoute
    }
    '/$year/$event/$session/': {
      id: '/$year/$event/$session/'
      path: '/'
      fullPath: '/$year/$event/$session/'
      preLoaderRoute: typeof YearEventSessionIndexRouteImport
      parentRoute: typeof YearEventSessionRouteRoute
    }
  }
}

interface YearEventSessionRouteRouteChildren {
  YearEventSessionIndexRoute: typeof YearEventSessionIndexRoute
}

const YearEventSessionRouteRouteChildren: YearEventSessionRouteRouteChildren = {
  YearEventSessionIndexRoute: YearEventSessionIndexRoute,
}

const YearEventSessionRouteRouteWithChildren =
  YearEventSessionRouteRoute._addFileChildren(
    YearEventSessionRouteRouteChildren,
  )

interface YearEventRouteRouteChildren {
  YearEventSessionRouteRoute: typeof YearEventSessionRouteRouteWithChildren
  YearEventIndexRoute: typeof YearEventIndexRoute
}

const YearEventRouteRouteChildren: YearEventRouteRouteChildren = {
  YearEventSessionRouteRoute: YearEventSessionRouteRouteWithChildren,
  YearEventIndexRoute: YearEventIndexRoute,
}

const YearEventRouteRouteWithChildren = YearEventRouteRoute._addFileChildren(
  YearEventRouteRouteChildren,
)

interface YearMapRouteRouteChildren {
  YearMapIndexRoute: typeof YearMapIndexRoute
}

const YearMapRouteRouteChildren: YearMapRouteRouteChildren = {
  YearMapIndexRoute: YearMapIndexRoute,
}

const YearMapRouteRouteWithChildren = YearMapRouteRoute._addFileChildren(
  YearMapRouteRouteChildren,
)

interface YearStandingsRouteRouteChildren {
  YearStandingsIndexRoute: typeof YearStandingsIndexRoute
}

const YearStandingsRouteRouteChildren: YearStandingsRouteRouteChildren = {
  YearStandingsIndexRoute: YearStandingsIndexRoute,
}

const YearStandingsRouteRouteWithChildren =
  YearStandingsRouteRoute._addFileChildren(YearStandingsRouteRouteChildren)

interface YearRouteChildren {
  YearEventRouteRoute: typeof YearEventRouteRouteWithChildren
  YearMapRouteRoute: typeof YearMapRouteRouteWithChildren
  YearStandingsRouteRoute: typeof YearStandingsRouteRouteWithChildren
}

const YearRouteChildren: YearRouteChildren = {
  YearEventRouteRoute: YearEventRouteRouteWithChildren,
  YearMapRouteRoute: YearMapRouteRouteWithChildren,
  YearStandingsRouteRoute: YearStandingsRouteRouteWithChildren,
}

const YearRouteWithChildren = YearRoute._addFileChildren(YearRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YearRoute: YearRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
